# Generated by Django 5.0.4 on 2024-08-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlanDict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="字典类型")),
                ("code", models.CharField(max_length=50, verbose_name="字典编号")),
                ("name", models.CharField(max_length=50, verbose_name="字典名称")),
            ],
            options={
                "verbose_name": "字典信息",
                "verbose_name_plural": "字典信息",
                "db_table": "plan_dict",
            },
        ),
        migrations.AddConstraint(
            model_name="plandict",
            constraint=models.UniqueConstraint(
                fields=("type", "code"), name="unique_type_code"
            ),
        ),
    ]
