# Generated by Django 5.0.4 on 2024-08-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_dicts", "0002_alter_plandict_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plandict",
            options={
                "ordering": ["type", "code"],
                "verbose_name": "字典信息",
                "verbose_name_plural": "字典信息",
            },
        ),
    ]
