# Generated by Django 5.0.4 on 2024-05-08 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='老师姓名')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(help_text='格式例如：2020-05-01', verbose_name='出生日期')),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='grades.grade', verbose_name='管理班级')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '老师信息',
                'verbose_name_plural': '老师信息',
                'db_table': 'teacher',
            },
        ),
    ]
